version: '3'

services:
  flarm_ogn_to_sbs:
    #build: ./
    image: ghcr.io/flyitalyadsb/flarm-ogn-to-sbs:latest
    container_name: flarm_ogn_to_sbs
    restart: always
    command:
      - --host
      - "flarm_ogn_to_sbs"
      - --listen-on
      - "3024"
      - --only-messages-with-icao

  readsb_ingest:
    image: ghcr.io/wiedehopf/readsb:dev
    container_name: readsb_ingest
    restart: unless-stopped
    entrypoint: /usr/local/bin/readsb-uuid
    command:
      - --net
      - --quiet
      - --net-connector=flarm_ogn_to_sbs,3024,sbs_in_mlat
      - --debug=nS
      - --net-beast-reduce-interval=0.2
