version: '3'

services:
  flarm-ogn-to-sbs:
    #build: ./
    image: ghcr.io/flyitalyadsb/flarm-ogn-to-sbs:latest
    container_name: flarm_ogn_to_sbs
    restart: always
    environment:
      - READSB_HOST=readsb_ingest
      - PORT=3022
      - ONLY_MESSAGES_WITH_ICAO=true
      - TIMEZONE=Europe/Rome
    networks:
      - flarm_network

networks:
  flarm_network:
    driver: bridge
